# Generated by Django 6.0.3 on 2026-05-19 00:04

import core.encrypted_fields
from django.db import migrations, models


def proteger_usuarios_existentes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    from core.privacy import document_hash, email_hash, normalize_email

    for user in User.objects.all().iterator():
        if user.email:
            user.email = normalize_email(user.email)
            user.email_hash = email_hash(user.email)
        if user.cpf_cnpj:
            user.cpf_cnpj_hash = document_hash(user.cpf_cnpj)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf_cnpj',
            field=core.encrypted_fields.EncryptedCharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.encrypted_fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=core.encrypted_fields.EncryptedCharField(max_length=20),
        ),
        migrations.RunPython(proteger_usuarios_existentes, migrations.RunPython.noop),
    ]
