# Generated by Django 6.0.3 on 2026-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certidao', models.CharField(choices=[('inteiro-teor', 'Certidão Inteiro Teor'), ('onus-reais', 'Certidão de Ônus Reais'), ('vintenaria', 'Certidão Vintenária'), ('atualizada', 'Certidão Atualizada + Ônus Reais + Ações')], max_length=50)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cartorio', models.CharField(max_length=255)),
                ('nome_solicitante', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('formato_certidao', models.CharField(choices=[('atualizada', 'Certidão Atualizada + Ônus Reais + Ações'), ('inteiro-teor', 'Certidão Inteiro Teor'), ('onus', 'Certidão de Ônus Reais'), ('vintenaria', 'Certidão Vintenária')], max_length=50)),
                ('tipo_busca', models.CharField(choices=[('matricula', 'Tenho matrícula/transcrição'), ('endereco', 'Tenho endereço do imóvel')], max_length=20)),
                ('tipo_identificacao', models.CharField(blank=True, choices=[('matricula', 'Matrícula'), ('transcricao', 'Transcrição')], max_length=20, null=True)),
                ('matriculas', models.TextField(blank=True, help_text='Separar múltiplas matrículas por vírgula', null=True)),
                ('cep_imovel', models.CharField(blank=True, max_length=9, null=True)),
                ('numero_imovel', models.CharField(blank=True, max_length=20, null=True)),
                ('rua_imovel', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro_imovel', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento_imovel', models.CharField(blank=True, max_length=255, null=True)),
                ('destino_utilizacao', models.TextField()),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
