# Generated by Django 6.0.3 on 2026-05-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimovel',
            name='formato_certidao',
        ),
    ]
