# Generated by Django 6.0.3 on 2026-05-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0004_orderimovel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimovel',
            name='user',
        ),
    ]
