# Generated by Django 6.0.3 on 2026-05-19 00:04

import core.encrypted_fields
from django.db import migrations, models


def proteger_pedidos_existentes(apps, schema_editor):
    OrderImovel = apps.get_model('certidao', 'OrderImovel')
    for pedido in OrderImovel.objects.all().iterator():
        pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0005_remove_orderimovel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimovel',
            name='bairro',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='bairro_imovel',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='cep',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='cep_imovel',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='complemento',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='complemento_imovel',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='destino_utilizacao',
            field=core.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='email',
            field=core.encrypted_fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='matriculas',
            field=core.encrypted_fields.EncryptedTextField(blank=True, help_text='Separar múltiplas matrículas por vírgula', null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='nome_solicitante',
            field=core.encrypted_fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='numero',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='numero_imovel',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='rua',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='rua_imovel',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='telefone',
            field=core.encrypted_fields.EncryptedCharField(max_length=20),
        ),
        migrations.RunPython(proteger_pedidos_existentes, migrations.RunPython.noop),
    ]
