# Generated by Django 6.0.3 on 2026-06-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0006_alter_orderimovel_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimovel',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', help_text='ID da sessão de checkout do Stripe', max_length=255),
        ),
    ]
