# Generated by Django 6.0.3 on 2026-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0007_orderimovel_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
