# Generated by Django 6.0.3 on 2026-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0008_cartorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorio',
            name='cidade',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
