# Generated by Django 6.0.3 on 2026-07-21 00:58

import core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0009_cartorio_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimovel',
            name='anos_retroagir',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderimovel',
            name='cpf_cnpj_busca',
            field=core.encrypted_fields.EncryptedCharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='tipo_busca',
            field=models.CharField(choices=[('matricula', 'Tenho matrícula/transcrição'), ('cpf_cnpj', 'CPF/CNPJ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderimovel',
            name='tipo_certidao',
            field=models.CharField(choices=[('inteiro-teor', 'Certidão Inteiro Teor'), ('inteiro-teor-livro-03', 'Certidão Inteiro Teor - Livro 03'), ('onus-reais', 'Certidão de Busca CPF/CNPJ'), ('vintenaria', 'Certidão de Filiação de Domínio'), ('atualizada', 'Certidão Atualizada + Ônus Reais + Ações')], max_length=50),
        ),
    ]
