CERTIDAO_SERVICE_PAGES = [
    {
        'slug': 'inteiro-teor',
        'tipo': 'inteiro-teor',
        'title': 'Certidão de Inteiro Teor do Imóvel',
        'short_title': 'Inteiro teor',
        'description': 'Documento indicado para consultar o teor completo da matrícula ou transcrição do imóvel junto ao cartório de registro.',
        'details': [
            'Ajuda em processos de compra, venda, financiamento, inventário e análise documental.',
            'A solicitação pode ser feita informando matrícula ou transcrição do imóvel e o cartório responsável.',
            'Também é conhecida em buscas como certidão de matrícula do imóvel, certidão de inteiro teor de imóvel e certidão de teor do imóvel.',
        ],
        'keywords': 'certidão de inteiro teor do imóvel, certidão de matrícula do imóvel, certidão de teor do imóvel, certidão de imóvel cartório',
    },
    {
        'slug': 'inteiro-teor-livro-03',
        'tipo': 'inteiro-teor-livro-03',
        'title': 'Certidão Inteiro Teor - Livro 03',
        'short_title': 'Livro 03',
        'description': 'Pedido para registros auxiliares relacionados ao imóvel, quando a informação está vinculada ao Livro 03 do cartório.',
        'details': [
            'Indicada quando o documento ou orientação recebida menciona registro auxiliar.',
            'O pedido exige o cartório de origem e o número de registro auxiliar para direcionar a busca.',
            'É uma alternativa para situações em que a matrícula comum não resolve toda a necessidade documental.',
        ],
        'keywords': 'certidão de registro de imóvel atualizada, certidão de transcrição do imóvel, certidão de averbação de imóvel',
    },
    {
        'slug': 'onus-reais',
        'tipo': 'onus-reais',
        'title': 'Certidão de Busca CPF/CNPJ',
        'short_title': 'Busca CPF/CNPJ',
        'description': 'Pesquisa positiva ou negativa de bens imobiliários vinculados a CPF ou CNPJ no cartório informado.',
        'details': [
            'Usada para verificar se há registros de propriedade ou bens associados a uma pessoa física ou jurídica.',
            'Também atende buscas por certidão negativa de propriedade de imóvel e certidão de busca negativa de imóvel.',
            'A solicitação é feita com CPF ou CNPJ válido e seleção do cartório competente.',
        ],
        'keywords': 'certidão de imóvel pelo CPF, certidão negativa de propriedade de imóvel, certidão de busca negativa de imóvel, consulta certidão de imóvel',
    },
    {
        'slug': 'filiacao-de-dominio',
        'tipo': 'vintenaria',
        'title': 'Certidão de Filiação de Domínio',
        'short_title': 'Filiação de domínio',
        'description': 'Certidão voltada ao histórico da titularidade do imóvel, com retroação pelo período necessário para análise.',
        'details': [
            'É útil quando a finalidade exige histórico do imóvel, cadeia dominial ou análise de titularidade anterior.',
            'No pedido, o solicitante informa matrícula ou transcrição e a quantidade de anos a retroagir.',
            'Pode ser procurada como certidão de histórico do imóvel, certidão de propriedade do imóvel ou certidão permanente de imóvel.',
        ],
        'keywords': 'certidão de histórico do imóvel, certidão de propriedade do imóvel, certidão permanente de imóvel, certidão de situação jurídica do imóvel',
    },
    {
        'slug': 'atualizada',
        'tipo': 'atualizada',
        'title': 'Certidão Atualizada + Ônus Reais + Ações',
        'short_title': 'Completa atualizada',
        'description': 'Opção completa para quem precisa de uma certidão de imóvel atualizada com informações registrais, ônus e ações.',
        'details': [
            'Indicada para venda de imóvel, financiamento, análise jurídica e confirmação da situação registral atual.',
            'Reúne informações procuradas como matrícula atualizada, ônus reais e ações relacionadas ao imóvel.',
            'É uma opção adequada para quem pergunta qual a certidão de imóvel mais completa.',
        ],
        'keywords': 'certidão de imóvel atualizada, certidão de matrícula de imóvel atualizada, certidão de ônus reais do imóvel, qual a certidão de imóvel mais completa',
    },
]


KEYWORD_CLUSTER = [
    'certidão de imóvel',
    'emissão de certidão de imóvel rural',
    'o que é certidão de imóvel',
    'emitir certidão de imóvel',
    'como tirar certidão de imóvel',
    'qual a certidão de imóvel mais completa',
    'solicitar certidão de imóvel online',
    'certidão de imóvel online',
    'certidão de imóvel rural',
    'certidão de imóvel atualizada',
    'certidão de averbação de imóvel',
    'certidão de matrícula de imóvel atualizada',
    'certidão de registro de imóvel atualizada',
    'certidão de matrícula atualizada do imóvel',
    'certidão de ônus atualizada do imóvel',
    'certidão de ônus reais do imóvel',
    'certidão negativa de imóvel',
    'certidão de inteiro teor do imóvel',
    'certidão de propriedade do imóvel',
    'certidão de busca negativa de imóvel',
    'certidão de dados cadastrais do imóvel',
    'certidão de matrícula de imóvel',
    'certidão de matrícula do imóvel',
    'certidão de ônus de imóvel',
    'certidão de ônus do imóvel',
    'certidão de valor venal do imóvel',
    'certidão negativa de débitos do imóvel',
    'certidão de escritura de imóvel',
    'certidão de imóvel cartório',
    'certidão de cadastro de imóvel rural',
    'certidão de imóvel pela internet',
    'consulta de certidão de imóvel',
    'emitir certidão de matrícula de imóvel',
    'emitir certidão de ônus do imóvel',
    'certidão de endereço do imóvel',
    'certidão de imóvel gratuita',
    'certidão de inteiro teor do imóvel online',
    'certidão de histórico do imóvel',
    'certidão de situação jurídica do imóvel',
    'certidão de localização do imóvel',
    'certidão de matrícula do imóvel online',
    'certidão de propriedade de imóvel',
    'certidão permanente de imóvel',
    'certidão para venda de imóvel',
    'certidão de transcrição do imóvel',
    'certidão de teor do imóvel',
    'certidão de imóvel urbano',
    'certidão negativa de ônus de imóvel',
    'certidão negativa de propriedade de imóvel',
    'certidão negativa de débitos de imóvel rural',
    'certidão de regularidade fiscal do imóvel',
    'certidão de inteiro teor de imóvel',
    'certidão de matrícula de imóvel online',
    'certidão de imóvel pelo endereço',
    'certidão de imóvel pelo CPF',
    'cartório certidão de imóvel',
    'solicitar certidão de matrícula do imóvel',
    'solicitar certidão de imóvel',
    'tirar certidão de imóvel',
    'obter certidão de imóvel',
    'consulta certidão de imóvel',
]


def get_service_page(slug):
    return next((item for item in CERTIDAO_SERVICE_PAGES if item['slug'] == slug), None)
