# Generated by Django 6.0.3 on 2026-07-24 20:19

import core.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', core.encrypted_fields.EncryptedCharField(max_length=255)),
                ('email', core.encrypted_fields.EncryptedEmailField(max_length=254)),
                ('telefone', core.encrypted_fields.EncryptedCharField(max_length=20)),
                ('mensagem', core.encrypted_fields.EncryptedTextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
