# Generated by Codex on 2026-07-25

import django.utils.timezone
from django.db import migrations, models


BLOG_POSTS = [
    {
        'title': 'O que é certidão de imóvel e quando solicitar',
        'slug': 'o-que-e-certidao-de-imovel',
        'excerpt': 'Entenda para que serve a certidão de imóvel, quais informações ela pode reunir e em quais situações ela costuma ser solicitada.',
        'content': """A certidão de imóvel é um documento emitido a partir dos registros do cartório competente. Ela ajuda a verificar informações como matrícula, transcrição, titularidade, histórico, ônus, averbaÃ§Ãµes e outros dados vinculados ao registro do imovel.

Esse tipo de documento costuma ser solicitado em compra e venda, financiamento, inventário, regularização, processos judiciais, análise de risco e confirmação da situação jurídica do imóvel.

Na Certidãobr, o pedido é feito online. O solicitante escolhe o tipo de certidão de imóvel, informa o cartório, preenche os dados necessários e acompanha o andamento pelo atendimento digital.""",
        'certidao_type': '',
        'meta_description': 'Entenda o que é certidão de imóvel, quando solicitar e como iniciar um pedido de certidão de imóvel online.',
        'seo_keywords': 'o que é certidão de imóvel, certidão de imóvel online, solicitar certidão de imóvel',
    },
    {
        'title': 'Como tirar certidão de matrícula de imóvel atualizada',
        'slug': 'como-tirar-certidao-de-matricula-de-imovel-atualizada',
        'excerpt': 'Veja quais dados ajudam no pedido de certidão de matrícula do imóvel e quando a versão atualizada é indicada.',
        'content': """Para tirar certidão de matrícula de imóvel atualizada, normalmente é preciso saber em qual cartório o imóvel está registrado e informar o número da matrícula ou transcrição. Esses dados direcionam a busca e reduzem risco de divergencia no pedido.

A certidão de matrícula atualizada do imóvel costuma ser usada para venda, financiamento, comprovação de propriedade, análise documental e conferências antes de fechar negócios.

Quando não houver certeza sobre qual documento pedir, a opção de certidão atualizada com ônus reais e ações pode ser mais completa, pois atende buscas relacionadas à situação jurídica do imóvel.""",
        'certidao_type': 'inteiro-teor',
        'meta_description': 'Saiba como tirar certidão de matrícula de imóvel atualizada e quais dados informar no pedido online.',
        'seo_keywords': 'certidão de matrícula de imóvel atualizada, emitir certidão de matrícula de imóvel, solicitar certidão de matrícula do imóvel',
    },
    {
        'title': 'Certidão de ônus reais do imóvel: para que serve',
        'slug': 'certidao-de-onus-reais-do-imovel-para-que-serve',
        'excerpt': 'Entenda a importância da certidão de ônus reais do imóvel e como ela ajuda na análise de pendências e restrições.',
        'content': """A certidão de ônus reais do imóvel é procurada quando a pessoa precisa verificar se existem registros que possam afetar o bem, como garantias, restrições ou apontamentos relevantes na matrícula.

Ela é especialmente importante em compra e venda, financiamento, inventário e análise jurídica. Também aparece em buscas como certidão de ônus atualizada do imóvel e certidão negativa de ônus de imóvel.

No pedido online, informe os dados do cartório e da matrícula quando a certidão for vinculada a um imóvel específico. Para pesquisas por pessoa, a busca por CPF/CNPJ pode ser mais adequada.""",
        'certidao_type': 'atualizada',
        'meta_description': 'Entenda para que serve a certidão de ônus reais do imóvel e quando solicitar esse documento online.',
        'seo_keywords': 'certidão de ônus reais do imóvel, certidão de ônus do imóvel, certidão negativa de ônus de imóvel',
    },
    {
        'title': 'Certidão negativa de propriedade de imóvel pelo CPF ou CNPJ',
        'slug': 'certidao-negativa-de-propriedade-de-imovel-pelo-cpf-ou-cnpj',
        'excerpt': 'Conheca a busca positiva ou negativa de bens imobiliarios e veja quando solicitar uma pesquisa por CPF ou CNPJ.',
        'content': """A certidão negativa de propriedade de imóvel ou busca negativa de imóvel é usada para verificar se há registros de bens imobiliários associados a um CPF ou CNPJ no cartório indicado.

Quando a pesquisa encontra registros, o resultado pode ser positivo. Quando não encontra, pode indicar inexistência de registro naquela serventia, conforme a busca realizada.

Esse pedido é diferente de uma certidão emitida por matrícula. Por isso, ao solicitar certidão de imóvel pelo CPF, escolha a opção de busca CPF/CNPJ e informe dados válidos.""",
        'certidao_type': 'onus-reais',
        'meta_description': 'Veja quando solicitar certidão negativa de propriedade de imóvel pelo CPF ou CNPJ e como funciona a busca online.',
        'seo_keywords': 'certidão de imóvel pelo CPF, certidão negativa de propriedade de imóvel, certidão de busca negativa de imóvel',
    },
    {
        'title': 'Qual a certidão de imóvel mais completa para venda',
        'slug': 'qual-a-certidao-de-imovel-mais-completa-para-venda',
        'excerpt': 'Compare inteiro teor, matrícula atualizada, ônus reais e a opção completa para venda e análise jurídica do imóvel.',
        'content': """Para venda de imóvel, a certidão mais completa costuma ser aquela que apresenta a situação atual da matrícula, ônus reais e eventuais ações relevantes. Por isso, a opção Certidão Atualizada + Ônus Reais + Ações é indicada quando a finalidade exige uma análise ampla.

A certidão de inteiro teor do imóvel também é importante, principalmente quando a pessoa precisa consultar o conteúdo completo do registro.

Antes de emitir certidão de imóvel, confirme a finalidade do documento, o cartório correto e os dados de matrícula ou transcrição. Isso ajuda a solicitar a certidao adequada e evitar retrabalho.""",
        'certidao_type': 'atualizada',
        'meta_description': 'Entenda qual certidão de imóvel é mais completa para venda, financiamento e análise jurídica.',
        'seo_keywords': 'qual a certidão de imóvel mais completa, certidão para venda de imóvel, certidão de imóvel atualizada',
    },
]


FAQS = [
    ('O que é certidão de imóvel?', 'É um documento emitido com base nos registros do cartório competente. Ele pode indicar dados da matricula, titularidade, onus, averbaÃ§Ãµes, historico ou situacao registral, conforme o tipo solicitado.', '', 'Conceitos', 1),
    ('Como tirar certidão de imóvel online?', 'Escolha o tipo de certidão, informe estado, cidade, cartório e os dados do imóvel ou da pessoa pesquisada. Depois, confira as informações, finalize o pedido e acompanhe o atendimento.', '', 'Pedido online', 2),
    ('Qual certidão de imóvel devo pedir?', 'Depende da finalidade. Para teor completo, use inteiro teor. Para pesquisa por CPF/CNPJ, use busca de bens. Para análise ampla de venda ou financiamento, a certidão atualizada com ônus reais e ações costuma ser mais indicada.', '', 'Escolha do pedido', 3),
    ('O que é certidão de matrícula do imóvel?', 'É a certidão relacionada à matrícula ou transcrição do imóvel. Ela ajuda a consultar dados registrais e pode ser solicitada de forma atualizada quando a finalidade exige informacoes recentes.', 'inteiro-teor', 'Matricula', 4),
    ('A certidão de inteiro teor do imóvel é online?', 'O pedido pode ser feito online pela Certidãobr. A emissão depende do cartório responsável e dos dados informados, como matrícula, transcrição e serventia de origem.', 'inteiro-teor', 'Inteiro teor', 5),
    ('O que significa certidão de ônus reais do imóvel?', 'É uma certidão usada para verificar apontamentos que podem afetar o imóvel, como restrições, garantias ou registros relevantes. Ela e comum em venda, financiamento e analise juridica.', 'atualizada', 'Onus reais', 6),
    ('Consigo solicitar certidão de imóvel pelo CPF?', 'Sim, quando o objetivo e pesquisar existência de bens vinculados a uma pessoa ou empresa no cartorio indicado. Nesse caso, escolha a opção de busca CPF/CNPJ.', 'onus-reais', 'Busca CPF/CNPJ', 7),
    ('O que é certidão negativa de propriedade de imóvel?', 'E o resultado de uma pesquisa que não localiza propriedade ou registro imobiliário para os dados consultados, conforme o cartório e o escopo da busca realizada.', 'onus-reais', 'Busca CPF/CNPJ', 8),
    ('Quando usar certidão de filiação de domínio?', 'Ela e indicada quando a finalidade exige histórico de titularidade, cadeia dominial ou retroação por determinado periodo. No pedido, informe os anos que deseja retroagir.', 'vintenaria', 'Historico', 9),
    ('Certidão de imóvel rural é emitida da mesma forma?', 'Alguns pedidos rurais podem exigir dados cadastrais ou documentos específicos, conforme a finalidade. Para registros imobiliários, a busca também depende do cartorio competente.', '', 'Imovel rural', 10),
    ('Posso pedir certidão de imóvel pelo endereço?', 'Quando o pedido disponível aceitar busca por endereço, informe CEP, rua, numero e bairro. Para os tipos atuais do formulário, a busca principal ocorre por matrícula, transcrição ou CPF/CNPJ.', '', 'Dados do imovel', 11),
    ('A certidão de imóvel gratuita está disponível?', 'Custos podem variar conforme tipo de certidão, cartório, taxas e serviços envolvidos. Antes de finalizar, confira o valor exibido para o tipo de pedido escolhido.', '', 'Custos', 12),
]


def seed_content(apps, schema_editor):
    BlogPost = apps.get_model('home', 'BlogPost')
    FAQItem = apps.get_model('home', 'FAQItem')
    now = django.utils.timezone.now()

    for post in BLOG_POSTS:
        BlogPost.objects.update_or_create(
            slug=post['slug'],
            defaults={**post, 'is_published': True, 'published_at': now},
        )

    for question, answer, certidao_type, category, sort_order in FAQS:
        FAQItem.objects.update_or_create(
            question=question,
            defaults={
                'answer': answer,
                'certidao_type': certidao_type,
                'category': category,
                'sort_order': sort_order,
                'is_published': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=420, verbose_name='resumo')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('certidao_type', models.CharField(blank=True, choices=[('', 'Geral'), ('inteiro-teor', 'CertidÃ£o Inteiro Teor'), ('inteiro-teor-livro-03', 'CertidÃ£o Inteiro Teor - Livro 03'), ('onus-reais', 'CertidÃ£o de Busca CPF/CNPJ'), ('vintenaria', 'CertidÃ£o de FiliaÃ§Ã£o de DomÃ­nio'), ('atualizada', 'CertidÃ£o Atualizada + Ã”nus Reais + AÃ§Ãµes')], default='', max_length=50, verbose_name='tipo de certidão')),
                ('meta_description', models.CharField(blank=True, default='', max_length=180)),
                ('seo_keywords', models.TextField(blank=True, default='', verbose_name='palavras-chave SEO')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Post do blog',
                'verbose_name_plural': 'Posts do blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240, verbose_name='pergunta')),
                ('answer', models.TextField(verbose_name='resposta')),
                ('certidao_type', models.CharField(blank=True, choices=[('', 'Geral'), ('inteiro-teor', 'CertidÃ£o Inteiro Teor'), ('inteiro-teor-livro-03', 'CertidÃ£o Inteiro Teor - Livro 03'), ('onus-reais', 'CertidÃ£o de Busca CPF/CNPJ'), ('vintenaria', 'CertidÃ£o de FiliaÃ§Ã£o de DomÃ­nio'), ('atualizada', 'CertidÃ£o Atualizada + Ã”nus Reais + AÃ§Ãµes')], default='', max_length=50, verbose_name='tipo de certidão')),
                ('category', models.CharField(blank=True, default='CertidÃ£o de imÃ³vel', max_length=120, verbose_name='categoria')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.RunPython(seed_content, noop_reverse),
    ]

